name: Update README

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: Readme-Workflows/recent-activity@v2.4.1
        with:
          FILE_NAME: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}