name: Update README

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check README.md exists
        run: ls -l && cat README.md

      - uses: Readme-Workflows/recent-activity@v2.4.1
        with:
          GH_USERNAME: CarlosECI
          CONFIG_FILE: .github/recent-activity.config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
