name: Update README

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check README.md exists
        run: ls -l && cat README.md

      - uses: jessicalostinspace/github-activity-readme@0.4.1
        with:
          MAX_LINES: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
